[http://cs231n.github.io/python-numpy-tutorial/#numpy]

In [1]:
import numpy as np

In [2]:
#pay attention to this:
arr1=[3,4,5,6,7]
print(type(arr1))

<class 'list'>


In [4]:
#now things change...
narr1=np.array(arr1)
print(type(narr1)) #repare que é narr1 e não arr1
#becomes a np.ndarray object, que vamos trabalhar aqui em ver as diferentes funções que podemos implementar nesse objeto
#isso inclui desde operacoes aritmeticas basicas até sistemas de equacoes lineares e estatistica bascia

<class 'numpy.ndarray'>


Numpy is an n dim array object or ndarray  
provides a fast and efficient way of storing homogeneous data  
we can have nd array w/ 1 dimension or 1 row and these are rank 1 arrays  
or we can have multidimensional arrays with more than one row [[row1, row2],[row3,row4]]

In [10]:
# multidimensional array

arr2=[[1,2,3,4],[3,4,5,6]]
print(type(arr2))
print(arr2)

<class 'list'>
[[1, 2, 3, 4], [3, 4, 5, 6]]


In [9]:
narr2=np.array(arr2)
print(type(narr2))
print(narr2)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [3 4 5 6]]


In [11]:
arr3=[[1,2,3,4],[3,4,5,6],[7,8,9,6]]

narr3=np.array(arr3)

print(narr3)
#multidimensional arrays w/ 3 rows and full cols

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 6]]


In [12]:
print(narr3.shape)


(3, 4)


In [13]:
#2*2 array with 0s

zer=np.zeros((2,2))
print(zer)

[[0. 0.]
 [0. 0.]]


In [16]:
#2*2 constant arrays

full=np.full((2,2),5)

print(full)

[[5 5]
 [5 5]]


In [18]:
ex3 = np.eye(4,4) #identidade
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
e = np.random.random((2,2)) # Create an array filled with random values
print (e)

[[0.39586866 0.31428252]
 [0.45512347 0.94953045]]


a[start:end] vai do item 0 até o item (end-1)  
a[start:] vai do item 0 até o último item  
a[:end] vai do item 0 até o item (end-1)  
a[:] é uma cópia do array inteiro  

In [22]:
a=[1,2,11,6,8,18,2]

na=np.array(a)

print(type(na))
print(na)

<class 'numpy.ndarray'>
[ 1  2 11  6  8 18  2]


In [23]:
print(na.shape) #its a rank 1 numpy array with 7 items

(7,)


In [24]:
#lets print out an elemant at index 2
print(na[2])

11


In [25]:
#isolate an entire chunk based on start index-end index
#print out values at start to end-1 index location

print(na[1:5])

[ 2 11  6  8]


In [26]:
#use a step of two

print(na[1:5:2])

[2 6]


In [31]:
print(na[-1]) 

2


In [35]:
#negative index
#print out values at start to end-1 index location

print(a[-6:-4]) #will isolate numbers till -4


[2, 11]


In [36]:
print(a[-3:-10])

[]


In [37]:
#print last item
print(a[-1])

2


In [38]:
#items start at one index and all the way to the end

print(a[3:])

[6, 8, 18, 2]


In [39]:
#print items from begining through end-1

print(a[:4])

[1, 2, 11, 6]


In [40]:
b=a[:] #copy an array
print(b)

[1, 2, 11, 6, 8, 18, 2]


In [44]:
#concatenate two numpy arrays

x=np.array([2,6,8,4])

y=np.array([11,8,2])

z=np.concatenate([y,x])

print(z)

[11  8  2  2  6  8  4]


In [43]:
#reverse the order
k=np.array(a[::-1])
print(k)

[ 2 18  8  6 11  2  1]


In [45]:
##Multi-dimensional array operations
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]

narr=np.array(arr) #convert array into numpy array

print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [46]:
print(narr[0]) #print first row at row index 0


[1 2 3 4]


In [47]:
print(narr[3])

[12  7 10  9]


In [49]:
print(narr[2,3]) #print contents of row with index 2 and column with index 3 [row,columm]
print(narr[3,2])

6
10


In [51]:
narr[3,2]=0 #replace value at a location
print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7  0  9]
 [ 2 11  8 10]]


In [52]:
#get the last row
print(narr[-1])

[ 2 11  8 10]


In [54]:
#get the last row
print(type(narr[-1]))

<class 'numpy.ndarray'>


In [55]:
#get the 2nd last
print(narr[-2])
# print rows and columns

print(narr[1:4,2:5]) #rows: 1 to 4-1 and columns 2 to 5-1

[12  7  0  9]
[[5 6]
 [9 6]
 [0 9]]


In [59]:
# print rows and columns

print(narr[1:9,2:8]) #rows: 1 to 4-1 and columns 2 to 5-1
#it doesn't complain if we extrapolate indexes!!!!!!!!

[[ 5  6]
 [ 9  6]
 [ 0  9]
 [ 8 10]]


In [60]:
###concatenation row and column wise

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

#concatenate row wise 

c=np.concatenate((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]]


# Some basic stats with numpy

In [64]:
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]
narr=np.array(arr) #convert array into numpy array
print (narr)

print('soma total =',narr.sum()) #sum all values of the array
print('soma por coluna =',narr.sum(axis=0)) #column wise sum
print('soma por linha =',narr.sum(axis=1)) #row wise sum


[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]
soma total = 127
soma por coluna = [25 32 35 35]
soma por linha = [10 18 30 38 31]


In [65]:
#mean and medians are measures of centre tendency

narr.mean(axis=0) #column means

array([5. , 6.4, 7. , 7. ])

In [66]:
np.median(narr,axis=1) #row median

array([2.5, 4.5, 7.5, 9.5, 9. ])

In [67]:
#variance in the data

np.std(narr) #standard dev

3.182373328193912

In [68]:
#percentile- value below which a given percentage of observations

np.percentile(narr,50,axis=1) #50th percentile

array([2.5, 4.5, 7.5, 9.5, 9. ])

In [21]:
import numpy as np
print("\nShowing some basic math on arrays:")
b=np.array([0,1,4,3,2])
print("max: {}".format(np.max(b)))
print("max: {}".format(np.average(b)))
print("max: {}".format(np.argmax(b)))
print("Shape of b: {}".format(b.shape))


Showing some basic math on arrays:
max: 4
max: 2.0
max: 2
Shape of b: (5,)


In [11]:
import numpy as np
#understand argmax
arr3=[[1,2,3,4],[3,4,5,6],[7,8,9,6]]

a=np.array(arr3)

j=np.argmax(a,axis=0) #vai buscar por coluna a posicao do primeiro elemento que for o maior de todos
k=np.argmax(a,axis=1) #vai buscar por linha a posicao do primeiro elemento que for o maior de todos
print(j)
print(k)

[2 2 2 1]
[3 3 2]


In [12]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0]))) #string.format(valores)


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int32'>


In [13]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.58429994 0.38079415 0.61742577]
 [0.2191784  0.92595338 0.84078298]
 [0.64787476 0.45725222 0.94182108]]


In [14]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3, 4)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


In [18]:
print(b)
print(type(b))

[0 1 4 3 2]
<class 'numpy.ndarray'>


In [19]:
print(a)
print(type(a))

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 6]]
<class 'numpy.ndarray'>


In [20]:
print(c)
print(type(c))

[[0.58429994 0.38079415 0.61742577]
 [0.2191784  0.92595338 0.84078298]
 [0.64787476 0.45725222 0.94182108]]
<class 'numpy.ndarray'>
